### ISSUE TITLE
Problem with importing in Typescript

### ISSUE THREAD

**Issue by ScottF77** [ludwiktrammer/nativescript-open-app#1]
Hi, I'm trying to use this package but I have problems importing it, I think that it maybe caused by `"main": "./open-app.js",` I don't think this file exists.

**Comment by ludwiktrammer** [comment]
Thank you for the report. It works for me. Could you make an experiment an change the line to `"main": "open-app",` in your local copy of the module? And report back to me if anything changes? Thanks.

**Comment by ludwiktrammer** [comment]
I'd guess this was fixed by 120960cfb502. Please let me know if the issue remains.
