### ISSUE TITLE
Can this support for launching IOS Settings app?

### ISSUE THREAD

**Issue by LSmint** [ludwiktrammer/nativescript-open-app#4]
Can this redirect user from current app to the IOS Settings page in order to change the access settings such as photos, camera, notification and etc.

**Comment by ludwiktrammer** [comment]
Even if you were able to open the settings app (it may be possible, I'm not sure), I think you would hit the problem of not being able to open a specific page within settings (see: #2).

**Comment by LSmint** [comment]
I got an idea to do it:
import * as utils from 'utils/utils';
utils.openUrl("app-settings:root=APP_NAME");
