### ISSUE TITLE
Cannot open another app on ios

### ISSUE THREAD

**Issue by Ihor912** [ludwiktrammer/nativescript-open-app#6]
If I try to open another app on Android it works well.

But about IOS:
Could you help me to understand how to get url (for instance "fb://") from this app: https://itunes.apple.com/hu/app/bankid-s%C3%A4kerhetsapp/id433151512?mt=8 ?

And also how to get correct value for "LSApplicationQueriesSchemes" in Info.plist file for this app?

I would appreciate any help.

**Comment by ludwiktrammer** [comment]
The app you want to poin to has to register the url scheme itself. If it hasn't then I think you are out of luck.

**Comment by ludwiktrammer** [comment]
Here you will find an instruction on finding app's url schemes (if there are any): https://stackoverflow.com/a/47418444/262618

**Comment by Ihor912** [comment]
Thank you for help!
