### ISSUE TITLE
open whatsapp with number

### ISSUE THREAD

**Issue by peppeg85** [ludwiktrammer/nativescript-open-app#8]
hello, is it possible to open the whatsapp app and pass a number to it?

**Comment by ludwiktrammer** [comment]
Opening whatsapp itself should be easy (`openApp("com.whatsapp")`), but unfortunately the plugin doesn't currently support passing anything.

I no longer use NativeScript for app development (I switched to Flutter), so it is very unlikely that I will have a need to add any new features to the plugins. But pull requests are welcome.

**Comment by peppeg85** [comment]
ok, thank you, in the meantime i solved with url:
```
let openUrl = require("tns-core-modules/utils/utils").openUrl
openUrl("https://api.whatsapp.com/send?phone=0000000") 
```
android opens directly the app with the number

thank you
